// This file is auto-generated by @hey-api/openapi-ts

export type GetOpenapiJsonResponse = (unknown);

export type GetOpenapiJsonError = unknown;

export type CreateUserData = {
    body: {
        username: string;
        password: string;
    };
};

export type CreateUserResponse = (({
    data: {
        id: string;
        username: string;
        password: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        labels: Array<{
            id: string;
            key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
            value: string;
            userId: string;
            createdTime: string;
            updatedTime: string;
            disabledTime: string;
            deletedTime?: string;
        }>;
        settings: Array<{
            id: string;
            key: string;
            value?: unknown;
            userId: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type CreateUserError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type GetUserData = {
    body?: ('null') | null;
};

export type GetUserResponse = (({
    data: {
        id: string;
        username: string;
        password: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        labels: Array<{
            id: string;
            key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
            value: string;
            userId: string;
            createdTime: string;
            updatedTime: string;
            disabledTime: string;
            deletedTime?: string;
        }>;
        settings: Array<{
            id: string;
            key: string;
            value?: unknown;
            userId: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type GetUserError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type QueryAnyUserData = {
    body: {
        filter: {
            id?: string;
            username?: string;
        };
        sort: Array<{
            key: 'id' | 'username';
            order: 'ASC' | 'DESC';
        }>;
        paging: {
            size: number;
            index: number;
        };
    };
};

export type QueryAnyUserResponse = (({
    data: {
        total: number;
        list: Array<{
            id: string;
            username: string;
            password: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
            labels: Array<{
                id: string;
                key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
                value: string;
                userId: string;
                createdTime: string;
                updatedTime: string;
                disabledTime: string;
                deletedTime?: string;
            }>;
            settings: Array<{
                id: string;
                key: string;
                value?: unknown;
                userId: string;
                createdTime: string;
                updatedTime: string;
                deletedTime?: string;
            }>;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type QueryAnyUserError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type DeleteAnyUserData = {
    body?: ('null') | null;
    path: {
        userId: string;
    };
};

export type DeleteAnyUserResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type DeleteAnyUserError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type SetAnyUserPasswordData = {
    body: {
        password: string;
    };
    path: {
        userId: string;
    };
};

export type SetAnyUserPasswordResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type SetAnyUserPasswordError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ListUserLabelData = {
    body?: ('null') | null;
};

export type ListUserLabelResponse = (({
    data: {
        total: number;
        list: Array<{
            id: string;
            key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
            value: string;
            userId: string;
            createdTime: string;
            updatedTime: string;
            disabledTime: string;
            deletedTime?: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ListUserLabelError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type UpsertUserLabelData = {
    body: {
        value: string;
    };
    path: {
        labelKey: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
    };
};

export type UpsertUserLabelResponse = (({
    data: {
        id: string;
        key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
        value: string;
        userId: string;
        createdTime: string;
        updatedTime: string;
        disabledTime: string;
        deletedTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type UpsertUserLabelError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type GetUserLabelData = {
    body?: ('null') | null;
    path: {
        labelKey: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
    };
};

export type GetUserLabelResponse = (({
    data: {
        id: string;
        key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
        value: string;
        userId: string;
        createdTime: string;
        updatedTime: string;
        disabledTime: string;
        deletedTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type GetUserLabelError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type DeleteUserLabelData = {
    body?: ('null') | null;
    path: {
        labelKey: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
    };
};

export type DeleteUserLabelResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type DeleteUserLabelError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ListAnyUserLabelData = {
    body?: ('null') | null;
    path: {
        userId: string;
    };
};

export type ListAnyUserLabelResponse = (({
    data: {
        total: number;
        list: Array<{
            id: string;
            key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
            value: string;
            userId: string;
            createdTime: string;
            updatedTime: string;
            disabledTime: string;
            deletedTime?: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ListAnyUserLabelError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type UpsertAnyUserLabelData = {
    body: {
        value: string;
    };
    path: {
        labelKey: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
        userId: string;
    };
};

export type UpsertAnyUserLabelResponse = (({
    data: {
        id: string;
        key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
        value: string;
        userId: string;
        createdTime: string;
        updatedTime: string;
        disabledTime: string;
        deletedTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type UpsertAnyUserLabelError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type GetAnyUserLabelData = {
    body?: ('null') | null;
    path: {
        labelKey: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
        userId: string;
    };
};

export type GetAnyUserLabelResponse = (({
    data: {
        id: string;
        key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
        value: string;
        userId: string;
        createdTime: string;
        updatedTime: string;
        disabledTime: string;
        deletedTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type GetAnyUserLabelError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type DeleteAnyUserLabelData = {
    body?: ('null') | null;
    path: {
        labelKey: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
        userId: string;
    };
};

export type DeleteAnyUserLabelResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type DeleteAnyUserLabelError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ListUserSecretData = {
    body?: ('null') | null;
};

export type ListUserSecretResponse = (({
    data: {
        total: number;
        list: Array<{
            id: string;
            key: string;
            value: string;
            userId: string;
            type: 'SignIn' | 'System' | 'User';
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
            disabledTime?: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ListUserSecretError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type CreateUserSecretData = {
    body: {
        type: 'SignIn' | 'System' | 'User';
        deletedTime?: string;
    };
};

export type CreateUserSecretResponse = (({
    data: {
        id: string;
        key: string;
        value: string;
        userId: string;
        type: 'SignIn' | 'System' | 'User';
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        disabledTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type CreateUserSecretError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type GetUserSecretData = {
    body?: ('null') | null;
    path: {
        secretKey: string;
    };
};

export type GetUserSecretResponse = (({
    data: {
        id: string;
        key: string;
        value: string;
        userId: string;
        type: 'SignIn' | 'System' | 'User';
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        disabledTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type GetUserSecretError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type DisableUserSecretData = {
    body?: ('null') | null;
    path: {
        secretKey: string;
    };
};

export type DisableUserSecretResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type DisableUserSecretError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type DeleteUserSecretData = {
    body?: ('null') | null;
    path: {
        secretKey: string;
    };
};

export type DeleteUserSecretResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type DeleteUserSecretError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ListAnyUserSecretData = {
    body?: ('null') | null;
    path: {
        userId: string;
    };
};

export type ListAnyUserSecretResponse = (({
    data: {
        total: number;
        list: Array<{
            id: string;
            key: string;
            value: string;
            userId: string;
            type: 'SignIn' | 'System' | 'User';
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
            disabledTime?: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ListAnyUserSecretError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type CreateAnyUserSecretData = {
    body: {
        type: 'SignIn' | 'System' | 'User';
        deletedTime?: string;
    };
    path: {
        userId: string;
    };
};

export type CreateAnyUserSecretResponse = (({
    data: {
        id: string;
        key: string;
        value: string;
        userId: string;
        type: 'SignIn' | 'System' | 'User';
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        disabledTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type CreateAnyUserSecretError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type GetAnyUserSecretData = {
    body?: ('null') | null;
    path: {
        secretKey: string;
        userId: string;
    };
};

export type GetAnyUserSecretResponse = (({
    data: {
        id: string;
        key: string;
        value: string;
        userId: string;
        type: 'SignIn' | 'System' | 'User';
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        disabledTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type GetAnyUserSecretError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type DisableAnyUserSecretData = {
    body?: ('null') | null;
    path: {
        secretKey: string;
        userId: string;
    };
};

export type DisableAnyUserSecretResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type DisableAnyUserSecretError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type DeleteAnyUserSecretData = {
    body?: ('null') | null;
    path: {
        secretKey: string;
        userId: string;
    };
};

export type DeleteAnyUserSecretResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type DeleteAnyUserSecretError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ListUserSettingData = {
    body?: ('null') | null;
};

export type ListUserSettingResponse = (({
    data: {
        total: number;
        list: Array<{
            id: string;
            key: string;
            value?: unknown;
            userId: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ListUserSettingError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type UpsertUserSettingData = {
    body?: {
        value?: unknown;
    };
    path: {
        settingKey: string;
    };
};

export type UpsertUserSettingResponse = (({
    data: {
        id: string;
        key: string;
        value?: unknown;
        userId: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type UpsertUserSettingError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type GetUserSettingData = {
    body?: ('null') | null;
    path: {
        settingKey: string;
    };
};

export type GetUserSettingResponse = (({
    data: {
        id: string;
        key: string;
        value?: unknown;
        userId: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type GetUserSettingError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type DeleteUserSettingData = {
    body?: ('null') | null;
    path: {
        settingKey: string;
    };
};

export type DeleteUserSettingResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type DeleteUserSettingError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ListAnyUserSettingData = {
    body?: ('null') | null;
    path: {
        userId: string;
    };
};

export type ListAnyUserSettingResponse = (({
    data: {
        total: number;
        list: Array<{
            id: string;
            key: string;
            value?: unknown;
            userId: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ListAnyUserSettingError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type UpsertAnyUserSettingData = {
    body?: {
        value?: unknown;
    };
    path: {
        settingKey: string;
        userId: string;
    };
};

export type UpsertAnyUserSettingResponse = (({
    data: {
        id: string;
        key: string;
        value?: unknown;
        userId: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type UpsertAnyUserSettingError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type GetAnyUserSettingData = {
    body?: ('null') | null;
    path: {
        settingKey: string;
        userId: string;
    };
};

export type GetAnyUserSettingResponse = (({
    data: {
        id: string;
        key: string;
        value?: unknown;
        userId: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type GetAnyUserSettingError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type DeleteAnyUserSettingData = {
    body?: ('null') | null;
    path: {
        settingKey: string;
        userId: string;
    };
};

export type DeleteAnyUserSettingResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type DeleteAnyUserSettingError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type VerifyPermissionData = {
    body: {
        service: string;
        operation: string;
        resource?: unknown;
    };
};

export type VerifyPermissionResponse = (({
    data: 'Allow' | 'Deny';
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type VerifyPermissionError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ListUserPermissionRoleData = {
    body?: ('null') | null;
};

export type ListUserPermissionRoleResponse = (({
    data: {
        total: number;
        list: Array<{
            id: string;
            name: string;
            /**
             * 是否为全局的角色，全局角色生效于所有用户
             */
            global?: boolean;
            description: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
            operations: Array<{
                id: string;
                roleId: string;
                effect: 'Allow' | 'Deny';
                service: string;
                operation: string;
                createdTime: string;
                updatedTime: string;
                deletedTime?: string;
            }>;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ListUserPermissionRoleError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ListPermissionRoleData = {
    body?: ('null') | null;
};

export type ListPermissionRoleResponse = (({
    data: {
        total: number;
        list: Array<{
            id: string;
            name: string;
            /**
             * 是否为全局的角色，全局角色生效于所有用户
             */
            global?: boolean;
            description: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
            operations: Array<{
                id: string;
                roleId: string;
                effect: 'Allow' | 'Deny';
                service: string;
                operation: string;
                createdTime: string;
                updatedTime: string;
                deletedTime?: string;
            }>;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ListPermissionRoleError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ListPermissionOperationData = {
    body?: ('null') | null;
};

export type ListPermissionOperationResponse = (({
    data: {
        total: number;
        list: Array<{
            service: string;
            operation: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ListPermissionOperationError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type CreatePermissionRoleData = {
    body: {
        name: string;
        /**
         * 是否为全局的角色，全局角色生效于所有用户
         */
        global?: boolean;
        description: string;
        operations: Array<{
            effect: 'Allow' | 'Deny';
            service: string;
            operation: string;
        }>;
    };
};

export type CreatePermissionRoleResponse = (({
    data: {
        id: string;
        name: string;
        /**
         * 是否为全局的角色，全局角色生效于所有用户
         */
        global?: boolean;
        description: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        operations: Array<{
            id: string;
            roleId: string;
            effect: 'Allow' | 'Deny';
            service: string;
            operation: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type CreatePermissionRoleError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type UpdatePermissionRoleData = {
    body: {
        name: string;
        /**
         * 是否为全局的角色，全局角色生效于所有用户
         */
        global?: boolean;
        description: string;
        operations: Array<{
            effect: 'Allow' | 'Deny';
            service: string;
            operation: string;
        }>;
    };
    path: {
        roleId: string;
    };
};

export type UpdatePermissionRoleResponse = (({
    data: {
        id: string;
        name: string;
        /**
         * 是否为全局的角色，全局角色生效于所有用户
         */
        global?: boolean;
        description: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        operations: Array<{
            id: string;
            roleId: string;
            effect: 'Allow' | 'Deny';
            service: string;
            operation: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type UpdatePermissionRoleError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type DeletePermissionRoleData = {
    body?: ('null') | null;
    path: {
        roleId: string;
    };
};

export type DeletePermissionRoleResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type DeletePermissionRoleError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type VerifyAnyUserPermissionData = {
    body: {
        service: string;
        operation: string;
        resource?: unknown;
    };
    path: {
        userId: string;
    };
};

export type VerifyAnyUserPermissionResponse = (({
    data: 'Allow' | 'Deny';
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type VerifyAnyUserPermissionError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ListAnyUserPermissionRoleData = {
    body?: ('null') | null;
    path: {
        userId: string;
    };
};

export type ListAnyUserPermissionRoleResponse = (({
    data: {
        total: number;
        list: Array<{
            id: string;
            name: string;
            /**
             * 是否为全局的角色，全局角色生效于所有用户
             */
            global?: boolean;
            description: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
            operations: Array<{
                id: string;
                roleId: string;
                effect: 'Allow' | 'Deny';
                service: string;
                operation: string;
                createdTime: string;
                updatedTime: string;
                deletedTime?: string;
            }>;
        }>;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ListAnyUserPermissionRoleError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type BindAnyUserPermissionRoleData = {
    body?: ('null') | null;
    path: {
        roleId: string;
        userId: string;
    };
};

export type BindAnyUserPermissionRoleResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type BindAnyUserPermissionRoleError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type UnbindAnyUserPermissionRoleData = {
    body?: ('null') | null;
    path: {
        roleId: string;
        userId: string;
    };
};

export type UnbindAnyUserPermissionRoleResponse = (({
    data: boolean;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type UnbindAnyUserPermissionRoleError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type ApplyCrossAuthTicketData = {
    body?: ('null') | null;
};

export type ApplyCrossAuthTicketResponse = (({
    data: {
        ticket: string;
        expiredTime: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type ApplyCrossAuthTicketError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type CheckCrossAuthTicketData = {
    body?: ('null') | null;
    path: {
        ticketId: string;
    };
};

export type CheckCrossAuthTicketResponse = (({
    data: {
        status: 'Applied' | 'Expired' | 'Finished';
        token?: string;
        userId?: string;
        expiredTime?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type CheckCrossAuthTicketError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type SignCrossAuthTicketData = {
    body?: ('null') | null;
    path: {
        ticketId: string;
    };
};

export type SignCrossAuthTicketResponse = (({
    data: {
        id: string;
        status: 'Applied' | 'Expired' | 'Finished';
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        signedUserId?: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type SignCrossAuthTicketError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type SignUpData = {
    body: {
        username: string;
        password: string;
    };
};

export type SignUpResponse = (({
    data: {
        token: string;
        userId: string;
        expiredTime: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type SignUpError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type SignInData = {
    body: {
        username: string;
        password: string;
        /**
         * 过期时间，单位为天，默认为 30 天
         */
        expiryDays?: number;
    };
};

export type SignInResponse = (({
    data: {
        token: string;
        userId: string;
        expiredTime: string;
    };
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type SignInError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type SignOutData = {
    body?: ('null') | null;
};

export type SignOutResponse = (({
    data?: unknown;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
}));

export type SignOutError = ({
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});

export type GlobalResponse = (string);

export type GlobalError = unknown;

export type ModelResponse = ({
    user: {
        id: string;
        username: string;
        password: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        labels: Array<{
            id: string;
            key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
            value: string;
            userId: string;
            createdTime: string;
            updatedTime: string;
            disabledTime: string;
            deletedTime?: string;
        }>;
        settings: Array<{
            id: string;
            key: string;
            value?: unknown;
            userId: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
        }>;
    };
    userLabel: {
        id: string;
        key: (string | 'System:LastSignInUserAgent' | 'System:LastSignInTime' | 'System:LastSignInIp' | 'System:LastOnlineUserAgent' | 'System:LastOnlineTime' | 'System:LastOnlineIp');
        value: string;
        userId: string;
        createdTime: string;
        updatedTime: string;
        disabledTime: string;
        deletedTime?: string;
    };
    userSecret: {
        id: string;
        key: string;
        value: string;
        userId: string;
        type: 'SignIn' | 'System' | 'User';
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        disabledTime?: string;
    };
    userSetting: {
        id: string;
        key: string;
        value?: unknown;
        userId: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
    };
    errorTypes: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
    permissionRole: {
        id: string;
        name: string;
        /**
         * 是否为全局的角色，全局角色生效于所有用户
         */
        global?: boolean;
        description: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
    };
    permissionEffect: 'Allow' | 'Deny';
    completePermissionRole: {
        id: string;
        name: string;
        /**
         * 是否为全局的角色，全局角色生效于所有用户
         */
        global?: boolean;
        description: string;
        createdTime: string;
        updatedTime: string;
        deletedTime?: string;
        operations: Array<{
            id: string;
            roleId: string;
            effect: 'Allow' | 'Deny';
            service: string;
            operation: string;
            createdTime: string;
            updatedTime: string;
            deletedTime?: string;
        }>;
    };
    response: ({
    data?: unknown;
    message: string;
    status: 'SUCCESS';
} | {
    message: string;
    status: 'UNKNOWN_ERROR' | 'INVALID_INPUT' | 'INCORRECT_PASSWORD' | 'AUTH_FAILED' | 'INVALID_TOKEN' | 'AUTH_TOKEN_EXPIRED' | 'CROSS_AUTH_TICKET_NOT_EXISTS' | 'PROHIBITED_BY_PERMISSION' | 'PERMISSION_ROLE_NOT_EXISTS' | 'USER_NOT_EXISTS' | 'USER_ALREADY_EXISTS' | 'USER_SETTING_NOT_FOUND' | 'USER_SECRET_NOT_FOUND' | 'NOT_IMPLEMENTED';
});
});

export type ModelError = unknown;